spring.application.name=tablero
spring.config.import=optional:file:.env[.properties]
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=true
spring.session.jdbc.initialize-schema=always

# --- CONFIGURACION DE SEGURIDAD (JWT) ---
# Tokens para perfiles (Usuarios del sistema) = 24h
jwt.user.secret=Y2xhdmVTZWNyZXRhTXV5U2VndXJhUGFyYUp3dEFwaVRhYmxlcm8yMDI2
jwt.user.expiration=86400000

# Tokens para clientes mediante enlace (Acceso restringido) = 1h
jwt.client.secret=Y2xhdmVTZWNyZXRhQ2xpZW50ZU11eVNlZ3VyYVBhcmFKd3RBcGlUYWJsZXIxMjM0
jwt.client.expiration=3600000